from typing import Any, Callable

class Epicenter:
    @staticmethod
    def record(variable_name: str, value: Any) -> None: ...
    @staticmethod
    def log(level: str, message: str) -> None: ...
    @staticmethod
    def callback(callback_name: str, data: list[dict[str, Any]]) -> None: ...
    @staticmethod
    def register_custom_encoder(type_class: type, encoder_func: Callable[..., str]) -> None: ...
    @staticmethod
    def register_custom_decoder(type_class: type, decoder_func: Callable[..., None]) -> None: ...
